<?php

use Illuminate\Database\Seeder;

class ProdiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $prodis = array(
            array(
                "fakultas_id" => 1,
                "nama" => "Ilmu Tanah",
                "kode" => "273",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 1,
                "nama" => "Proteksi Tanaman",
                "kode" => "282",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 1,
                "nama" => "Agroekoteknologi Kampus Dharmasraya ",
                "kode" => "286",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 1,
                "nama" => "Agroekoteknologi",
                "kode" => "103",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 1,
                "nama" => "Agribisnis",
                "kode" => "104",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 2,
                "nama" => "Pendidikan Dokter",
                "kode" => "9",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 2,
                "nama" => "Psikologi",
                "kode" => "117",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 2,
                "nama" => "Kebidanan",
                "kode" => "236",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 3,
                "nama" => "Kimia",
                "kode" => "13",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 3,
                "nama" => "Biologi",
                "kode" => "14",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 3,
                "nama" => "Matematika",
                "kode" => "15",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 3,
                "nama" => "Fisika",
                "kode" => "16",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 4,
                "nama" => "Ilmu Hukum",
                "kode" => "18",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 5,
                "nama" => "Ilmu Ekonomi",
                "kode" => "19",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 5,
                "nama" => "Manajemen",
                "kode" => "20",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 5,
                "nama" => "Akuntansi",
                "kode" => "21",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 5,
                "nama" => "Ilmu Ekonomi Kampus Payakumbuh ",
                "kode" => "284",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 5,
                "nama" => "Manajemen Kampus Payakumbuh ",
                "kode" => "285",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 6,
                "nama" => "Ilmu Peternakan",
                "kode" => "26",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 7,
                "nama" => "Teknik Mesin",
                "kode" => "30",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 7,
                "nama" => "Teknik Sipil",
                "kode" => "31",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 7,
                "nama" => "Teknik Industri",
                "kode" => "32",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 7,
                "nama" => "Teknik Lingkungan",
                "kode" => "33",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 7,
                "nama" => "Teknik Elektro",
                "kode" => "34",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 8,
                "nama" => "Ilmu Sejarah",
                "kode" => "35",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 8,
                "nama" => "Sastra Indonesia",
                "kode" => "36",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 8,
                "nama" => "Sastra Inggris",
                "kode" => "37",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 8,
                "nama" => "Sastra Minangkabau",
                "kode" => "38",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 8,
                "nama" => "Sastra Jepang",
                "kode" => "89",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 9,
                "nama" => "Sosiologi",
                "kode" => "40",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 9,
                "nama" => "Antropologi Sosial",
                "kode" => "41",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 9,
                "nama" => "Ilmu Politik",
                "kode" => "42",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 9,
                "nama" => "Ilmu Administrasi Negara",
                "kode" => "43",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 9,
                "nama" => "Ilmu Hubungan Internasional",
                "kode" => "93",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 9,
                "nama" => "Ilmu Komunikasi",
                "kode" => "100",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 10,
                "nama" => "Farmasi",
                "kode" => "12",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 11,
                "nama" => "Teknologi Hasil Pertanian",
                "kode" => "7",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 11,
                "nama" => "Teknik Pertanian",
                "kode" => "8",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 11,
                "nama" => "Teknologi Industri Pertanian",
                "kode" => "294",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 12,
                "nama" => "Ilmu Kesehatan Masyarakat",
                "kode" => "11",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 12,
                "nama" => "Ilmu Gizi ",
                "kode" => "283",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 13,
                "nama" => "Ilmu Keperawatan",
                "kode" => "10",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 13,
                "nama" => "Ners",
                "kode" => "293",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 14,
                "nama" => "Pendidikan Dokter Gigi",
                "kode" => "102",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 15,
                "nama" => "Sistem Komputer",
                "kode" => "101",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 15,
                "nama" => "Sistem Informasi",
                "kode" => "119",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 16,
                "nama" => "Bioteknologi ",
                "kode" => "287",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 16,
                "nama" => "Ilmu Penyuluhan dan Komunikasi Pembangunan ",
                "kode" => "288",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 16,
                "nama" => "Pembangunan Wilayah Pedesaan ",
                "kode" => "289",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 16,
                "nama" => "Ilmu Lingkungan ",
                "kode" => "290",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 16,
                "nama" => "Pengelolaan Terpadu Sumberdaya Alam ",
                "kode" => "291",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
            array(
                "fakultas_id" => 16,
                "nama" => "Pembangunan Perumahan dan Pemukiman",
                "kode" => "292",
                "kode_dikti" => NULL,
                "akreditasi" => NULL,
            ),
        );
        \App\Prodi::insert($prodis);
    }
}
